### ISSUE TITLE
Report-match

### ISSUE THREAD

**Issue by nlsui** [DecentralCardGame/CardchainCs#2]
Currently the report match transaction takes two player-Ids and no match-Id (probably generated during the transaction)

The match-Id ingame gets generated at the start of the game, so it would be better if the transaction takes the already generated Id.

Also genereating the match-ID by the transaction means the clients have to wait for the server until the transaction is finished which would be bad for the UX-flow

**Comment by patrickwieth** [comment]
How do different game servers sync match ids?

**Comment by nlsui** [comment]
We agreed on two TransactionsTypes to report matches:
- OpenMatch(player1, player2, deck1, deck2) => matchId
   can only be executed by Server at the start of a match
- ReportMatchResult (matchId, result)
   reported by both clients and the server
   majority determines actual result

**Comment by lxgr-linux** [comment]
There is just one problem, which is, that the chain will just give vote rights, that have actually been played, and not the whole deck. Which is not know at the matches beginning

**Comment by patrickwieth** [comment]
He can send the whole deck as played cards

**Comment by patrickwieth** [comment]
But maybe it makes sense to build it directly like intended. Commit the played cards at the end and let the player vote when waiting for the next game

**Comment by nlsui** [comment]
I would argue that its way better to vote on cards asap after playing

**Comment by patrickwieth** [comment]
Well we can do it also like that, it will just be additional work to change it later. I guess the current version is preferred because it is simpler to implement?

**Comment by nlsui** [comment]
no, I its preferred because in my opinion its way better to vote on cards asap after playing.
Implementationwise there should not be much of a difference (tracking played cards should not be much work).
But we have to push the decklists at some point to check if the player actually owns the cards
